### ISSUE TITLE
Scopes list not the same as scopes in screenshot

### ISSUE THREAD

**Issue by jdelbarre-axway** [Axway/amplify-integration-labs#2]
The list of scopes "crm.schemas.companies.write crm.schemas.contacts.write crm.schemas.deals.read crm.schemas.deals.write crm.objects.owners.read crm.objects.contacts.write crm.objects.companies.write crm.lists.write crm.objects.companies.read crm.lists.read crm.objects.deals.read crm.schemas.contacts.read crm.objects.deals.write crm.objects.contacts.read crm.schemas.companies.read crm.objects.custom.read crm.schemas.custom.read" does not match the screenshot with the selected scopes. The screenshot is missing crm.objects.custom.read and crm.schemas.custom.read.

This is happening in https://github.com/Axway/amplify-integration-labs/blob/f90e820f72e4849c7843048cdb1d483fce13cc26/cloud-integration/assets/hubspot-connection.md

**Comment by lbrenman** [comment]
Fixed. Thx!
